Repository woowa-techcamp-2020/hkb-12, pull requests merged in 2020-08, with the labels that each got.

#39 dailyHistory 데이터 가공하는 함수 리펙토링
  client/src/App/components/dailyHistory/index.js
  client/src/App/pages/hkb/index.js
  client/src/App/store/index.js
  client/src/App/utils.js
Labels: feature, frontend

#42 네비게이션 이벤트 작업 분리
  client/src/App/components/layout/container/navigation/index.js
  client/src/App/index.js
Labels: feature, frontend

#43 캘린더 월별 정보 가져오기
  .eslintrc
  client/src/App/components/calendar/calendar.scss
  client/src/App/components/calendar/index.js
  client/src/App/components/hkbSum/hkbSum.scss
  client/src/App/pages/calendar/index.js
  client/src/App/pages/hkb/hkb.scss
  client/src/App/pages/hkb/index.js
  client/src/App/utils.js
Labels: feature, frontend

#44 daysOfHistory 함수 개선
  client/src/App/utils.js
Labels: bug, enhancement, feature, frontend

#47 달력에서 렌더링 안되는 문제 해결
  client/src/App/components/hkbForm/index.js
  client/src/App/pages/hkb/index.js
  client/src/App/utils.js
Labels: bug, feature, frontend

#45 프론트엔드 api와 endpoint 추가
  client/src/App/apis/endpoints.js
  client/src/App/apis/index.js
  client/src/App/pages/hkb/index.js
  server/routes/index.js
Labels: feature, frontend

#49 백엔드 파일명 변경
  server/controllers/hkbhist-controller.js
  server/models/category-dto.js
  server/models/hkbhist-dto.js
  server/models/index.js
  server/models/payment-dto.js
  server/models/user-dto.js
  server/repository/hkbhist-repo.js
  server/routes/category.js
  server/routes/hkbhist.js
  server/routes/payment.js
  server/routes/user.js
  server/services/hkbhist-service.js
Labels: backend, feature

#46 프론트엔드 chart 예제 추가
  client/src/App/components/expenseFilter/expenseFilter.scss
  client/src/App/components/expenseFilter/index.js
  client/src/App/components/graph/bar/bar.scss
  client/src/App/components/graph/bar/index.js
  client/src/App/components/graph/circle/circle.scss
  client/src/App/components/graph/circle/index.js
  client/src/App/components/graph/index.js
  client/src/App/components/graph/line/index.js
  client/src/App/components/graph/line/line.scss
  client/src/App/components/hkbForm/index.js
  client/src/App/components/index.js
  client/src/App/components/layout/header/header.scss
  client/src/App/event/graph.js
  client/src/App/event/hkbHist.js
  client/src/App/event/index.js
  client/src/App/index.js
  client/src/App/pages/graph/graph.scss
  client/src/App/pages/graph/index.js
  client/src/App/store/index.js
  client/src/App/utils.js
Labels: feature, frontend

#52 프론트엔드 통계 페이지 수정
  client/src/App/pages/graph/index.js
  client/src/App/utils.js
Labels: feature, frontend

#51 Passport& OAuth 로그인 구현
  client/public/bdb1985971c1dfcf7e92957f98a4dbfb.svg
  client/src/App/apis/index.js
  client/src/App/assets/images/logo-github.svg
  client/src/App/index.js
  client/src/App/pages/index.js
  client/src/App/pages/login/index.js
  client/src/App/pages/login/login.scss
  client/src/App/route.js
  client/src/App/store/index.js
  server/app.js
  server/controllers/user-controller.js
  server/package-lock.json
  server/package.json
  server/passport.js
  server/repository/user-repo.js
  server/routes/index.js
  server/routes/user.js
  server/services/hkbhist-service.js
  server/services/user-service.js
Labels: backend, feature, frontend

#53 프론트엔드 년도, 달 네비게이션 추가
  client/src/App/components/layout/container/navigation/index.js
  client/src/App/event/index.js
  client/src/App/event/navigation.js
  client/src/App/index.js
  client/src/App/store/index.js
Labels: enhancement, feature, frontend

#54 라우팅 잘못된 페이지 렌더링 해결
  client/src/App/event/navigation.js
  client/src/App/index.js
Labels: bug, frontend

#55 페이지 라우팅 처리 변경
  client/src/App/event/navigation.js
  client/src/App/index.js
  client/src/App/route.js
Labels: bug, frontend

#56 popstate에서 앞으로가기 뒤로가기 동작에러 해결
  client/src/App/event/navigation.js
Labels: bug, frontend

#57 페이지 라우팅될때 이벤트리스너 등록
  client/src/App/index.js
Labels: feature, frontend

#58 프론트엔드 내역 페이지 내역 추가 구현
  client/src/App/apis/endpoints.js
  client/src/App/apis/index.js
  client/src/App/components/dailyHistory/index.js
  client/src/App/components/hkbForm/index.js
  client/src/App/components/hkbSum/index.js
  client/src/App/components/layout/container/container.scss
  client/src/App/components/layout/layout.scss
  client/src/App/event/hkbHist.js
  client/src/App/index.js
  client/src/App/pages/hkb/index.js
  client/src/App/store/index.js
  client/src/App/utils.js
  client/webpack.config.js
  server/controllers/category-controller.js
  server/controllers/hkbhist-controller.js
  server/controllers/payment-controller.js
  server/models/hkbhist-dto.js
  server/repository/category-repo.js
  server/repository/hkbhist-repo.js
  server/repository/payment-repo.js
  server/routes/category.js
  server/routes/index.js
  server/routes/payment.js
  server/services/category-service.js
  server/services/hkbhist-service.js
  server/services/payment-service.js
Labels: backend, feature, frontend

#67 호스팅안되는 문제 해결
  client/public/index.html
  server/services/user-service.js
Labels: backend, bug

#68 포트 및 아이피주소 변경
  client/src/App/apis/endpoints.js
  server/services/user-service.js
Labels: backend, bug, frontend

#69 엔드포인트 URL 변경
  client/src/App/apis/endpoints.js
Labels: bug, frontend

#70 엔드포인트에 '/' 제거
  client/src/App/apis/endpoints.js
Labels: bug, frontend

#72 프록시로 URL 제어
  client/package.json
  client/src/App/apis/endpoints.js
Labels: bug

#66 프론트엔드 통계페이지 수정
  client/src/App/utils.js
Labels: enhancement, feature, frontend

#71 내역 페이지 내역 삭제 구현
  client/src/App/apis/index.js
  client/src/App/components/dailyHistory/caseHistory/caseHistory.scss
  client/src/App/components/dailyHistory/caseHistory/index.js
  client/src/App/components/dailyHistory/index.js
  client/src/App/components/hkbForm/hkbForm.scss
  client/src/App/components/hkbForm/index.js
  client/src/App/event/hkbHist.js
  client/src/App/pages/hkb/index.js
  client/src/App/store/index.js
  server/controllers/hkbhist-controller.js
  server/repository/hkbhist-repo.js
  server/services/hkbhist-service.js
Labels: backend, feature, frontend

#73 프론트엔드 달력 라우팅
  client/src/App/components/calendar/calendar.scss
  client/src/App/event/navigation.js
  client/src/App/pages/calendar/index.js
  client/src/App/pages/graph/index.js
  client/src/App/pages/hkb/index.js
  client/src/App/store/index.js
Labels: feature, frontend

#74 프론트엔드 통계 페이지 오류 수정
  client/src/App/components/graph/circle/index.js
  client/src/App/utils.js
Labels: bug, frontend

#75 내역 페이지 내역 수정
  client/src/App/apis/index.js
  client/src/App/event/hkbHist.js
  client/src/App/store/index.js
  server/controllers/hkbhist-controller.js
  server/repository/hkbhist-repo.js
  server/services/hkbhist-service.js
Labels: backend, feature, frontend

#76 달력페이지 수정
  client/src/App/components/calendar/calendar.scss
  client/src/App/components/calendar/index.js
Labels: feature, frontend

#78 달력에 연도 정보 추가
  client/src/App/components/calendar/index.js
  client/src/App/pages/calendar/index.js
Labels: feature, frontend

#77 백엔드 Update HkbHist 형식 수정
  server/repository/hkbhist-repo.js
Labels: backend, bug

#79 프론트엔드 네비게이션 오류 수정
  client/src/App/event/hkbHist.js
  client/src/App/event/navigation.js
  client/src/App/pages/calendar/index.js
  client/src/App/pages/graph/index.js
  client/src/App/pages/hkb/index.js
  client/src/App/utils.js
Labels: bug, frontend

#80 프론트엔드 원형 그래프 수정
  client/src/App/components/expenseFilter/expenseFilter.scss
  client/src/App/components/expenseFilter/index.js
  client/src/App/components/graph/bar/index.js
  client/src/App/pages/graph/index.js
  client/src/App/utils.js
Labels: bug

#81 백엔드 라우팅 설정
  server/controllers/hkbhist-controller.js
  server/controllers/payment-controller.js
  server/controllers/user-controller.js
  server/models/user-dto.js
  server/repository/hkbhist-repo.js
  server/repository/user-repo.js
  server/routes/category.js
  server/routes/hkbhist.js
  server/routes/payment.js
  server/services/user-service.js
Labels: backend, feature

#82 프론트엔드 통계 페이지 구현
  client/src/App/components/graph/line/index.js
  client/src/App/components/graph/line/line.scss
  client/src/App/pages/graph/index.js
  client/src/App/utils.js
Labels: feature, frontend

#83 프론트엔드 통계 페이지 오류 수정
  client/src/App/pages/graph/index.js
  client/src/App/utils.js
Labels: bug, frontend

#84 프론트엔드 hkbhist 페이지 내역 추가 오류 수정
  client/src/App/event/hkbHist.js
Labels: feature, frontend

#85 결제수단 모달 구현
  client/src/App/apis/index.js
  client/src/App/components/layout/header/header.scss
  client/src/App/components/layout/header/index.js
  client/src/App/components/layout/header/modalBtn/index.js
  client/src/App/components/layout/index.js
  client/src/App/components/modal/header/index.js
  client/src/App/components/modal/index.js
  client/src/App/components/modal/modal.scss
  client/src/App/components/modal/payment/addForm/index.js
  client/src/App/components/modal/payment/index.js
  client/src/App/components/modal/payment/list/index.js
  client/src/App/components/modal/payment/list/item/index.js
  client/src/App/event/index.js
  client/src/App/event/modal.js
  client/src/App/index.js
  server/controllers/payment-controller.js
  server/repository/payment-repo.js
  server/routes/payment.js
  server/services/payment-service.js
Labels: backend, feature, frontend

#86 입력하고 input 비우기
  client/src/App/event/modal.js
Labels: feature, frontend

#87 프론트엔드 통계 페이지 꺾은선 그래프 좌표 오류 수정
  client/src/App/components/graph/line/index.js
  client/src/App/pages/graph/index.js
  client/src/App/utils.js
Labels: bug, frontend

#88 프론트엔드 hkbSum 컴포넌트 기능 구현
  client/src/App/components/calendar/calendar.scss
  client/src/App/components/dailyHistory/caseHistory/index.js
  client/src/App/components/hkbSum/index.js
  client/src/App/event/hkbSum.js
  client/src/App/event/index.js
  client/src/App/index.js
Labels: feature, frontend
