Repository woowa-techcamp-2020/hkb-12, pull requests merged in 2020-07, with the labels that each got.

#4 webpack 설정
  client/package-lock.json
  client/package.json
  client/public/bundle.js
  client/public/index.html
  client/src/index.js
  client/webpack.config.js
Labels: feature, frontend

#16 프론트엔드 observer 패턴 적용
  client/src/index.js
  client/src/store.js
Labels: feature, frontend

#19 스토어 디렉토리 이동 및 변수, 함수명 변경
  client/src/index.js
  client/src/store/index.js
Labels: feature, frontend

#26 프론트엔드 스켈레톤 코드 작성
  client/public/index.html
  client/src/assets/reset.scss
  client/src/components/index.js
  client/src/components/layout/container/container.scss
  client/src/components/layout/container/index.js
  client/src/components/layout/container/navigation/index.js
  client/src/components/layout/container/navigation/navigation.scss
  client/src/components/layout/header/header.scss
  client/src/components/layout/header/index.js
  client/src/components/layout/index.js
  client/src/components/layout/layout.scss
  client/src/index.js
  client/src/index.scss
  client/src/pages/calendar/index.js
  client/src/pages/graph/index.js
  client/src/pages/hkb/index.js
  client/src/pages/index.js
  client/src/route.js
  client/src/store/index.js
Labels: feature, frontend

#20 ESLint 적용
  .eslintrc
  .gitignore
  client/src/index.js
  client/src/store/index.js
  package-lock.json
  package.json
  server/app.js
  server/routes/index.js
  server/routes/users.js
Labels: feature, frontend

#27 ESLint를 적용하고 코드를 일관되게 수정
  client/src/components/index.js
  client/src/components/layout/container/index.js
  client/src/components/layout/container/navigation/index.js
  client/src/components/layout/header/index.js
  client/src/components/layout/index.js
  client/src/index.js
  client/src/pages/calendar/index.js
  client/src/pages/graph/index.js
  client/src/pages/hkb/index.js
  client/src/pages/index.js
  client/src/route.js
Labels: feature, frontend

#28 reset css 설정 및 클래스명 변경
  client/src/assets/reset.scss
  client/src/components/layout/container/navigation/index.js
  client/src/index.js
  client/src/index.scss
Labels: feature, frontend

#29 Backend skeleton 코드 작성
  .eslintrc
  .gitignore
  client/package-lock.json
  client/package.json
  client/public/bundle.js
  client/src/index.js
  client/webpack.config.js
  server/app.js
  server/controllers/hkbHistController.js
  server/models/categoryDTO.js
  server/models/hkbHistDTO.js
  server/models/index.js
  server/models/paymentDTO.js
  server/models/userDTO.js
  server/package-lock.json
  server/package.json
  server/pool.js
  server/repository/hkbHistRepo.js
  server/routes/category.js
  server/routes/hkbhist.js
  server/routes/index.js
  server/routes/payment.js
  server/routes/user.js
  server/routes/users.js
  server/services/hkbHistService.js
Labels: backend, feature, frontend

#34 달력 디자인
  client/src/components/calendar/calendar.scss
  client/src/components/calendar/index.js
  client/src/components/index.js
  client/src/index.js
  client/src/pages/calendar/index.js
  client/src/pages/index.js
  client/src/route.js
Labels: feature, frontend

#35 ClientSide 라우팅 설정
  .gitignore
  client/public/bundle.js
  client/src/index.js
  client/webpack.config.js
  server/app.js
  server/repository/hkbHistRepo.js
Labels: backend, feature

#33 hkbhist page 개발
  client/src/components/caseHistory/index.js
  client/src/components/dailyHistory/caseHistory/caseHistory.scss
  client/src/components/dailyHistory/caseHistory/index.js
  client/src/components/dailyHistory/dailyHistory.scss
  client/src/components/dailyHistory/index.js
  client/src/components/hkbForm/hkbForm.scss
  client/src/components/hkbForm/index.js
  client/src/components/hkbSum/hkbSum.scss
  client/src/components/hkbSum/index.js
  client/src/components/index.js
  client/src/components/layout/container/container.scss
  client/src/components/layout/container/navigation/index.js
  client/src/components/layout/container/navigation/navigation.scss
  client/src/index.js
  client/src/pages/hkb/hkb.scss
  client/src/pages/hkb/index.js
  client/src/store/index.js
  client/src/utils.js
  server/models/hkbHistDTO.js
Labels: feature, frontend

#37 네비게이션에서 월정보 받아오기
  client/src/components/calendar/index.js
  client/src/pages/calendar/index.js
  client/src/pages/hkb/index.js
Labels: feature, frontend

#38 리펙토링
  .eslintrc
  client/src/App/assets/reset.scss
  client/src/App/components/calendar/calendar.scss
  client/src/App/components/calendar/index.js
  client/src/App/components/dailyHistory/caseHistory/caseHistory.scss
  client/src/App/components/dailyHistory/caseHistory/index.js
  client/src/App/components/dailyHistory/dailyHistory.scss
  client/src/App/components/dailyHistory/index.js
  client/src/App/components/expenseFilter/index.js
  client/src/App/components/graph/bar/index.js
  client/src/App/components/graph/circle/index.js
  client/src/App/components/graph/index.js
  client/src/App/components/graph/line/index.js
  client/src/App/components/hkbForm/hkbForm.scss
  client/src/App/components/hkbForm/index.js
  client/src/App/components/hkbSum/hkbSum.scss
  client/src/App/components/hkbSum/index.js
  client/src/App/components/index.js
  client/src/App/components/layout/container/container.scss
  client/src/App/components/layout/container/index.js
  client/src/App/components/layout/container/navigation/index.js
  client/src/App/components/layout/container/navigation/navigation.scss
  client/src/App/components/layout/header/header.scss
  client/src/App/components/layout/header/index.js
  client/src/App/components/layout/index.js
  client/src/App/components/layout/layout.scss
  client/src/App/components/modal/header/index.js
  client/src/App/components/modal/index.js
  client/src/App/components/modal/payment/addForm/index.js
  client/src/App/components/modal/payment/list/index.js
  client/src/App/components/modal/payment/list/item/index.js
  client/src/App/index.js
  client/src/App/index.scss
  client/src/App/pages/calendar/index.js
  client/src/App/pages/graph/index.js
  client/src/App/pages/hkb/hkb.scss
  client/src/App/pages/hkb/index.js
  client/src/App/pages/index.js
  client/src/App/route.js
  client/src/App/store/index.js
  client/src/App/utils.js
  client/src/index.js
  client/src/pages/graph/index.js
Labels: bug, feature, frontend
